routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::singularResourceParameters();
Route::pattern('id', '[0-9]+');
Route::pattern('slug', '[a-z0-9\-]+');
Route::pattern('slug1', '[a-z0-9\-]+');
Route::pattern('slug2', '[a-z0-9\-]+');
Route::pattern('slug3', '[a-z0-9\-]+');


//------------------ Trang quản trị (CMS) ------------------//
Route::group(['middleware' => 'admin'], function()
{
	Route::group(['prefix' => 'admin'], function() {
		Route::get('/', function(){
			return 'admin';
		});
	});
});

//------------------ Trang người dùng ------------------//
//Trang chủ
Route::get('/','HomeController@index');

//Trang dành cho ứng viên (khách không truy cập được)
Route::group(['middleware' => 'auth'], function()
{
	//Việc làm đã lưu
	Route::get('/viec-lam-da-luu', 'UserCustom\SaveJobController@index');
	//Xóa việc làm
	Route::post('/viec-lam-da-luu/xoa', 'UserCustom\SaveJobController@destroy');

	//Sửa thông tin cá nhân
	Route::get('/thong-tin-ca-nhan', 'UserCustom\ProfileController@edit');
	Route::post('/thong-tin-ca-nhan', 'UserCustom\ProfileController@update');

	//Đổi mật khẩu
	Route::get('/doi-mat-khau', 'UserCustom\ChangePasswordController@edit');
	Route::post('/doi-mat-khau', 'UserCustom\ChangePasswordController@update');

});

//Lưu việc làm (ajax)
Route::get('/luu-viec-lam/{id}', 'UserCustom\SaveJobController@store');

//Đăng xuất
Route::get('logout', function(){
	Auth::logout();
	return redirect('/');
});
//Đăng nhập, đăng ký
Auth::routes();

//Đăng nhập facebook
Route::get('/facebook/redirect', 'Auth\SocialController@redirectToProvider');
Route::get('/facebook/callback', 'Auth\SocialController@handleProviderCallback');

//Trang đăng ký nhận bản tin qua email
Route::get('/dang-ky','SubscribeController@create');
Route::post('/dang-ky','SubscribeController@store');
Route::get('/dang-ky/thong-bao.html', 'SubscribeController@success');

//Tìm kiếm
Route::get('/tim-kiem','SearchController@index');
Route::get('/tim-kiem/ajax/{id}','SearchController@loadIndustrialZone');

//Việc làm theo ngành nghề
Route::get('/nganh-nghe', 'CarrerController@category');
Route::get('/nganh-nghe/{slug1}', 'CarrerController@index');

//Kiểm trang url là Page hay trang việc làm theo tỉnh thành
Route::get('/{slug1}', 'Slug1Controller@index');

//Kiểm tra url là trang công ty hay trang khu công nghiệp
Route::get('/{slug1}/{slug2}', 'Slug2Controller@index');

//Chi tiết việc làm
Route::get('/{slug1}/{slug2}/{slug3}.html', 'JobController@index');

app/Models/IndustrialZone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class IndustrialZone extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [];
    protected $table = 'industrial_zones';

    public function jobLists()
    {
        return $this->hasMany('App\Models\JobList', 'industrial_id');
    }

    public function companies()
    {
        return $this->hasMany('App\Models\Company', 'industrial_id');
    }

    public function province()
    {
        return $this->belongsTo('App\Models\Province', 'province_id');
    }

    public function getLocationAttribute($value)
    {
        if ($value) {
            $result = explode(', ', $value);
        }else{
            $result = null;
        }
        return $result;
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}

app/Models/Province.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    protected $table = 'province';

    protected $fillable = [''];

    public function jobLists()
    {
        return $this->hasMany('App\Models\JobList')->orderBy('updated_at', 'desc');
    }

    public function company()
    {
        return $this->hasMany('App\Models\Company');
    }

    public function industrialZones()
    {
        return $this->hasMany('App\Models\IndustrialZone')->orderBy('ranking', 'asc');
    }
    
    public function getImagesAttribute($value)
    {
        if ($value){
            $result = explode(',', $value);
        }else{
            $result = null;
        }
        return $result;
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}

resources/views/company.blade.php
@extends($layout)

@section('title', $company->meta_title)
@section('description', $company->meta_description)

@section('content')
<div id="main-top">
    <div class="container">
        <div class="main-top">
            <h3>{{ $company->name }}</h3>
            <div class="col-md-4 main-top-img">
                <img src="{!! $company->images ? $company->images : '/image/no-image.png' !!}'" title="{{ $company->name }}" alt="{{ $company->name }}" width="498" height="315">
            </div>
            <div class="col-md-5 desc">
                {!! str_limit($company->description, 400) !!}
            </div>
            <div class="col-md-3 map">
                <div class="box">
                    {!! $company->location !!}
                    {{--
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3723.6653029790314!2d105.7919243148278!3d21.04607399256311!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab3a9f4447a3%3A0x3c2e56b445e47c0c!2zMTQxIEhvw6BuZyBRdeG7kWMgVmnhu4d0LCBOZ2jEqWEgVMOibiwgQ-G6p3UgR2nhuqV5LCBIw6AgTuG7mWksIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1480728562673" width="100%" height="215" frameborder="0" style="border:0" allowfullscreen></iframe>
                    --}}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="main">
    <div class="container">
        <div class="row">
            <div id="content" class="col-md-8">
                @if ($job_lists->count() > 0)
                <div class="form-list-job">
                    <div class="box-head">
                        <h3>VIỆC LÀM MỚI NHẤT</h3>
                    </div>
                    <div class="box-body">
                        @if($job_lists->count() > 0)
                            <div class="list-jobs">
                                @foreach ($job_lists as $job_list)
                                <div class="list-item">
                                    <div class="row">
                                        <a href="/{{ $job_list->province->slug }}/{{ $job_list->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{{ $job_list->company->logo ? $job_list->company->logo : '/image/no-image.png' }}" alt="{{ $job_list->company->name }}"></a>
                                        <div class="list-item-content col-md-10 col-xs-9">
                                            <div  class="company-job"><h2><a href="/{{ $job_list->province->slug }}/{{ $job_list->industrialZone->slug }}/{{ $job_list->slug }}.html">{{ $job_list->job_title }}</a></h2>{{-- <span class="label label-danger">HOT</span> --}}</div>
                                            <div class="row">
                                                @if ($job_list->jobCarrers->count() > 0)
                                                <div class="col-md-4 mp">
                                                    <i class="fa fa-suitcase" aria-hidden="true"></i>
                                                    @foreach ($job_list->jobCarrers as $jobCarrer)
                                                        <a href="/nganh-nghe/{{ $jobCarrer->slug }}">{{ $jobCarrer->name }}</a>
                                                    @endforeach
                                                </div>
                                                @endif
                                                <div class="col-md-4 mp">
                                                    <span><i class="fa fa-usd" aria-hidden="true"></i> {{ $job_list->jobWage ? $job_list->jobWage->name : number_format($job_list->job_wage) }}</span>
                                                </div>
                                                <div class="col-md-4 mp">
                                                    <span><i class="fa fa-stop-circle-o" aria-hidden="true"></i>{{ $job_list->job_ended_at }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                            <div class="page">
                                {!! $job_lists->render() !!}
                            </div>
                        @else
                            Không tìm thấy việc làm nào trong công ty này
                        @endif
                    </div>
                </div>
                @else
                    <p>Công ty không có việc làm mới nào</p>
                @endif
            </div>
            <div id="sidebar" class="col-md-4">
                @if($industrialzone_jobs->count() > 0)
                    <div class="form-list-right">
                        <div class="box-head">
                            <h3>Việc làm khu công nghiệp</h3>
                        </div>
                        <div class="box-body">
                            @foreach ($industrialzone_jobs as $industrialzone_job)
                                <div class="list-item">
                                    <div class="row">
                                        <a href="/{{ $industrialzone_job->province->slug }}/{{ $industrialzone_job->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{!! $industrialzone_job->company->logo ? $industrialzone_job->company->logo : '/image/no-image.png' !!}" alt="{{ $industrialzone_job->company->name }}"></a>
                                        <div class=" col-md-10 col-xs-9 list-item-content">
                                            <div class="company-job"><h4><a href="/{{ $industrialzone_job->province->slug }}/{{ $industrialzone_job->industrialZone->slug }}/{{ $industrialzone_job->slug }}.html">{{ $industrialzone_job->job_title }}</a></h4><span class="label label-danger">HOT</span></div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <i class="fa fa-usd" aria-hidden="true"></i>  {{ $industrialzone_job->jobWage ? $industrialzone_job->jobWage->name : number_format($industrialzone_job->job_wage) }}
                                                </div>
                                                <div class="col-md-6">
                                                    <i class="fa fa-stop-circle-o" aria-hidden="true"></i>{{ $industrialzone_job->job_ended_at }}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                @endif

                {{--
                <div class="form-list-right">
                    <div class="box-head">
                        <h3>Việc làm khu công nghiệp</h3>
                    </div>
                    <div class="box-body">
                        <div class="list-item">
                            <div class="row">
                                <a href="congtythuockcn.html" class="col-md-2 col-xs-3 list-item-logo"><img src="image/0acfdcf8a2c1.jpg" alt="Logo công ty"></a>
                                <div class=" col-md-10 col-xs-9 list-item-content">
                                    <div class="company-job"><h4><a href="PostCVthuocKCN.html">Trưởng Phòng Tài Chính Kế Toán</a></h4><span class="label label-danger">MỚI</span></div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <i class="fa fa-usd" aria-hidden="true"></i>20 triệu
                                        </div>
                                        <div class="col-md-6">
                                            <i class="fa fa-stop-circle-o" aria-hidden="true"></i>20-10-2016
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                --}}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/industrialZone.blade.php
@extends($layout)

@section('title', $industrial_zone->meta_title)
@section('description', $industrial_zone->meta_desciption)

@section('head')
    <style type="text/css">
        #map-canvas { height: 100% }
    </style>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDfNk5eVWmQB9e6ApnWzICLNIY5lUXpOBw"></script>
    <script type="text/javascript">

        // Function khởi tạo google map
        function initialize()
        {
            // Config google map
            var mapOptions = {
                // Tọa độ muốn hiển thị ban đầu (tung độ,vỹ độ)
                center: new google.maps.LatLng(10.771971, 106.697845),
                // Mức độ zoom
                zoom: 8
            };

            // Hiển thị map lên bản đồ (div#map-canvas)
            var map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
        }

        // Gán hàm initialize vào trong sự kiện load dom google map
        google.maps.event.addDomListener(window, 'load', initialize);
    </script>
@endsection

@section('content')
    <div id="main-top">
        <div class="container">
            <h3>Việc làm {{ $industrial_zone->name }}</h3>
            <div class="main-top">
                <div class="col-md-4 main-top-img">
                    <img src="{!! $industrial_zone->image_path ? $industrial_zone->image_path : '/image/no-image.png' !!}" title="{{ $industrial_zone->name }}" alt="{{ $industrial_zone->name }}" width="498">
                </div>
                <div class="col-md-5 desc">
                    {!! str_limit($industrial_zone->introduction, 400) !!}
                </div>

                <div class="col-md-3 map">
                    <div class="box">
                        <div id="map-canvas"/>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="main">
        <div class="container">
            <div class="row">
                <div id="content" class="col-md-8">
                    @if ($job_lists->count() > 0)
                    <div class="form-list-job">
                        <div class="box-head">
                            <h3>VIỆC LÀM MỚI NHẤT</h3>
                        </div>
                        <div class="box-body">
                            <div class="list-jobs">
                                @foreach ($job_lists as $job_list)
                                    <div class="list-item">
                                        <div class="row">
                                            <a href="/{{ $job_list->province->slug }}/{{ $job_list->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{!! $job_list->company->logo ? $job_list->company->logo : '/image/no-image.png' !!}" alt="{{ $job_list->company->name }}"></a>
                                            <div class="list-item-content col-md-10 col-xs-9">
                                                <div  class="company-job"><h2><a href="/{{ $job_list->province->slug }}/{{ $job_list->industrialZone->slug }}/{{ $job_list->slug }}.html">{{ $job_list->job_title }}</a></h2><!-- <span class="label label-danger">HOT</span> --></div>
                                                <div class="row">
                                                    <div class="col-md-4 mp">
                                                        @if ($job_list->jobCarrers)
                                                            <i class="fa fa-suitcase" aria-hidden="true"></i>
                                                            @foreach ($job_list->jobCarrers as $jobCarrer)
                                                                <a href="/nganh-nghe/{{ $jobCarrer->slug }}">{{ $jobCarrer->name }}</a>
                                                            @endforeach
                                                        @endif
                                                    </div>
                                                    <div class="col-md-4 mp">
                                                        <span><i class="fa fa-usd" aria-hidden="true"></i> {{ $job_list->jobWage ? $job_list->jobWage->name : number_format($job_list->job_wage) }}</span>
                                                    </div>
                                                    <div class="col-md-4 mp">
                                                        <span><i class="fa fa-stop-circle-o" aria-hidden="true"></i>{{ $job_list->job_ended_at }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <div class="page">
                                {!! $job_lists->render() !!}
                            </div>
                        </div>
                    </div>
                    @else
                        <p>Không có việc làm mới trong khu công nghiệp này</p>
                    @endif
                </div>

                <div id="sidebar" class="col-md-4">
                    <div class="form-list-right">
                        <div class="box-head">
                            <h3>Công ty trong khu công nghiệp</h3>
                        </div>
                        <div class="box-body">
                            @foreach ($company_industrialzones as $company_industrialzone)
                            <div class="list-item">
                                <div class="row">
                                    <a href="/{{ $company_industrialzone->province->slug }}/{{ $company_industrialzone->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{{ $company_industrialzone->logo ? $company_industrialzone->logo : '/image/no-image.png' }}" alt="{{ $company_industrialzone->name }}"></a>
                                    <div class=" col-md-10 col-xs-9 list-item-content">
                                        <div class="company-job"><h4><a href="/{{ $company_industrialzone->province->slug }}/{{ $company_industrialzone->slug }}">{{ $company_industrialzone->name }}</a></h4></div>
                                        <div class="company-num">
                                            Đang có <span style="color:red">{{ number_format($company_industrialzone->jobLists->count()) }}</span> việc
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>

                    <div class="video">
                        <div class="box-head">
                            <h3>Video</h3>
                        </div>
                        <div class="box-body" style="margin: 0;padding: 0;">
                            <iframe width="100%" height="300" style="padding: 0; border: 0;margin: 0;" src="https://www.youtube.com/embed/haLuAFxOwWQ">
                            </iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/page.blade.php
@extends($layout)

@section('title', $page->meta_title)
@section('description', $page->meta_description)

@section('content')
<div id="main">
    <div class="container">
        <div class="row">
            <div id="page-detail">
                <div class="box-body">
                    <h1 class="text-center">{{ $page->name }}</h1>
                    <div class="detail" style="padding: 30px">
                        {!! $page->content !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/province.blade.php
@extends($layout)

@section('title', $province->meta_title)
@section('keywords', '')
@section('description', $province->meta_description)

@section('content')
<div id="main-top">
    <div class="container">
        <h3>Việc làm {{ $province->name }}</h3>
        <div class="main-top">
            <div id="slides" class="col-md-5 main-top-img">
                <div class="slides">
                    @if($province->images)
                        @foreach ($province->images as $image)
                            <a href="/{{ $province->slug }}"><img src="{{ $image }}" title="{{ $province->name }}" alt="{{ $province->name }}" width="498" height="315"></a>
                        @endforeach
                    @else
                        <a href="/{{ $province->slug }}"><img src="/image/no-image.png" title="{{ $province->name }}" alt="{{ $province->name }}" width="498" height="315"></a>
                    @endif
                </div>
            </div>
            <div class="col-md-7 desc">
                {!! $province->introduction !!}
            </div>
        </div>
    </div>
</div>

<div id="main">
    <div class="container">
        <div class="row">
            <div id="content" class="col-md-8">
                <div class="form-list-job">
                    <div class="box-head">
                        <h3>VIỆC LÀM MỚI NHẤT</h3>
                    </div>
                    <div class="box-body">
                        <div class="list-jobs">
                            @foreach ($job_lists as $job_list)
                            <div class="list-item">
                                <div class="row">
                                    <a href="/{{ $job_list->province->slug }}/{{ $job_list->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{{ $job_list->company->logo ? $job_list->company->logo : '/image/no-image.png' }}" alt="{{ $job_list->company->name }}"></a>
                                    <div class="list-item-content col-md-10 col-xs-9">
                                        <div  class="company-job"><h2><a href="/{{ $job_list->province->slug }}/{{ $job_list->industrialZone->slug }}/{{ $job_list->slug }}.html">{{ $job_list->job_title }}</a></h2>{{-- <span class="label label-danger">HOT</span> --}}</div>
                                        <div class="row">
                                            <div class="col-md-8 mp">
                                                <i class="fa fa-address-book" aria-hidden="true"></i><a href="/{{ $job_list->province->slug }}/{{ $job_list->company->slug }}">{{ $job_list->company->name }}</a>
                                            </div>
                                            <div class="col-md-4 mp">
                                                <span><i class="fa fa-usd" aria-hidden="true"></i> {{ $job_list->jobWage ? $job_list->jobWage->name : number_format($job_list->job_wage) }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>
                        <div class="page">
                            {!! $job_lists->render() !!}
                        </div>

                    </div>
                </div>

                @if ($expired_job_lists->count() > 0)
                <div class="form-list-job">
                    <div class="box-head">
                        <h3>Việc làm tuyển gấp</h3>
                    </div>
                    <div class="box-body">
                        <div class="list-jobs">
                            @foreach ($expired_job_lists as $expired_job_list)
                            <div class="list-item">
                                <div class="row">
                                    <a href="/{{ $expired_job_list->province->slug }}/{{ $expired_job_list->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{!! $expired_job_list->company->logo ? $expired_job_list->company->logo : '/image/no-image.png' !!}" alt="{{ $expired_job_list->company->name }}"></a>
                                    <div class="list-item-content col-md-10 col-xs-9">
                                        <div class="company-job"><h2><a href="/{{ $expired_job_list->province->slug }}/{{ $expired_job_list->industrialZone->slug }}/{{ $expired_job_list->slug }}.html">{{ $expired_job_list->job_title }}</a></h2><span class="label label-danger">GẤP</span></div>
                                        <div class="row">
                                            <div class="col-md-8 mp">
                                                <i class="fa fa-address-book" aria-hidden="true"></i><a href="/{{ $expired_job_list->province->slug }}/{{ $expired_job_list->company->slug }}">{{ $expired_job_list->company->name }}</a>
                                            </div>
                                            <div class="col-md-4 mp">
                                                <i class="fa fa-stop-circle-o" aria-hidden="true"></i>
                                                @if ($expired_job_list->subJobEndedAt())
                                                Còn <span style="color:red">{{ $expired_job_list->subJobEndedAt() }}</span> ngày để nộp HS
                                                @else
                                                    <span style="color:red">Hết hạn</span>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                @endif
            </div>

            <div id="sidebar" class="col-md-4">
                @if($high_job_lists->count() > 0)
                <div class="form-list-right">
                    <div class="box-head">
                        <h3>Việc làm hấp dẫn</h3>
                    </div>
                    <div class="box-body">
                        @foreach ($high_job_lists as $high_job_list)
                        <div class="list-item">
                            <div class="row">
                                <a href="/{{ $high_job_list->province->slug }}/{{ $high_job_list->company->slug }}" class="col-md-2 col-xs-3 list-item-logo"><img src="{!! $high_job_list->company->logo ? $high_job_list->company->logo : '/image/no-image.png' !!}" alt="{{ $high_job_list->company->name }}"></a>
                                <div class=" col-md-10 col-xs-9 list-item-content">
                                    <div class="company-job"><h4><a href="/{{ $high_job_list->province->slug }}/{{ $high_job_list->industrialZone->slug }}/{{ $high_job_list->slug }}.html">{{ $high_job_list->job_title }}</a><span class="label label-danger">HOT</span></h4></div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <i class="fa fa-usd" aria-hidden="true"></i>  {{ $high_job_list->jobWage ? $high_job_list->jobWage->name : number_format($high_job_list->job_wage) }}
                                        </div>
                                        <div class="col-md-6">
                                            <i class="fa fa-stop-circle-o" aria-hidden="true"></i>{{ $high_job_list->job_ended_at }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
                @endif

                <div class="video">
                    <div class="box-head">
                        <h3>Video</h3>
                    </div>
                    <div class="box-body">
                        <iframe width="100%" height="300" src="https://www.youtube.com/embed/haLuAFxOwWQ">
                        </iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection